-- 创建应用专用用户并授权
CREATE USER yuan WITH PASSWORD 'Passvord2025';
GRANT CONNECT ON DATABASE dev_marketplace TO yuan;
GRANT CREATE ON DATABASE dev_marketplace TO yuan;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO yuan;
GRANT USAGE, CREATE ON SCHEMA public TO yuan;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO yuan;